version: '3.8'
services:
  node-app:
    build: .
    ports:
      - '3000:3000' # HTTP server
      - '3001:3001' # Metrics server

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3002:3000'
